### ISSUE TITLE
Changes in your plugin basis atto_equation

### ISSUE THREAD

**Issue by Kathrin84** [geoffrowland/moodle-editor_atto-computing#1]
Hi,

we're using your atto plugin and are updating to Moodle 2.9. I've tested your plugin and it works fine in the new Moodle version.
Nevertheless, I just wanted to tell you that there have been some cosmetic code changes in the javascript files of atto_equation.
You could transfer those changes into the code of your plugin to stay consistent with the basis.

Kind regards
Kathrin

**Comment by geoffrowland** [comment]
OK will look to merge the changes.

**Comment by geoffrowland** [comment]
Hi Kathrin
I have now merged the latest atto_equation code with atto_computing. I'll also do the same for atto_equation ASAP.
Thanks for the 'nudge'.
Geoff
